# Pull base image.
FROM quay.io/eris/build
MAINTAINER Eris Industries <support@erisindustries.com>

#-----------------------------------------------------------------------------
# install epm

# set the repo and copy in files
ENV REPO $GOPATH/src/github.com/eris-ltd/eris-pm
COPY ./epm_artifact $REPO/epm_artifact

# install eris-pm
RUN chmod +x $REPO/epm_artifact
RUN chown $USER:$USER $REPO/epm_artifact
RUN cp $REPO/epm_artifact $INSTALL_BASE/epm
RUN rm $REPO/epm_artifact

#-----------------------------------------------------------------------------
# root dir

# persist data, set user
RUN chown --recursive $USER:$USER /home/$USER
VOLUME /home/$USER/.eris
WORKDIR /home/$USER/.eris
USER $USER
CMD ["epm", "--chain", "chain:46657", "--sign", "keys:4767" ]
